use_frameworks!

target 'CarouselView_Example' do
  pod 'CarouselView', :path => '../'

  target 'CarouselView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
